time_precision: NSECS
logging_level: WARNING
reactors:
  machine:
    parameters:
      data_model_path: "data_model/feedthrough_machine.yml"
      step_size: 0.1
    reactors:
      message_filter:
        logging_level: ERROR
