from enum import StrEnum


class Operation(StrEnum):
    """Operations shared by all simulation participants."""

    REGISTER = "register"
    RESPONSE = "response"
    ERROR = "error"
    INITIALIZED = "initialized"
    READY = "ready"
    CAPABILITIES = "capabilities"
    INITIALIZE = "initialize"
    SET_INPUTS = "set_inputs"
    GET_OUTPUTS = "get_outputs"
    DRY_RUN = "dry_run"
    SIMULATE = "simulate"
    COMMIT = "commit"
    DISCARD_CANDIDATE = "discard_candidate"
    RESYNC = "resync"
    ENTER_EVENT_MODE = "enter_event_mode"
    EVENT_ITERATION = "event_iteration"
    ENTER_STEP_MODE = "enter_step_mode"
    SAVE_STATE = "save_state"
    RESTORE_STATE = "restore_state"
    FREE_STATE = "free_state"
    CLOCK_STATE = "clock_state"
    SET_CLOCK = "set_clock"
    SET_CLOCK_INTERVAL = "set_clock_interval"
    SET_CLOCK_SHIFT = "set_clock_shift"
    TERMINATE = "terminate"
    RESET = "reset"
