name: "TrainDoor" # name of the machine
machine_category: "unknown" # category of the machine
machine_type: "unknown" # type of the machine
machine_model: "unknown" # model of the machine
description: "" # description of the machine
root:
  !!FolderNode
  name: "TrainDoor"
  description: ""
  children:
    - !!NumericalVariableNode
      name: "timestamp"
      description: ""
      measure_unit: "NoneMeasureUnits.NONE"
      initial_value: 0
    - !!BooleanVariableNode
      name: "opened"
      description: ""
      measure_unit: "NoneMeasureUnits.NONE"
      initial_value: False
    - !!BooleanVariableNode
      name: "requested"
      description: ""
      measure_unit: "NoneMeasureUnits.NONE"
      initial_value: False
    - !!AsyncMethodNode
      name: "operation"
      description: ""
      parameters:
        - !!StringVariableNode
          name: "operation"
          description: ""
          default_value: "c"
      returns:
        - !!StringVariableNode
          name: "result"
          description: ""
